name: canvas_clock
description: creativecreatorormaybenot's entry to the Flutter clock challenge.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The clock customizer is not part of the actual clock face.
  flutter_clock_helper:
    path: ../flutter_clock_helper

flutter:
  # The clock helper uses Material design icons, hence, this is added.
  uses-material-design: true
